# -*- coding: utf-8 -*-
"""Rock_scissor_paper_game.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ssKZce4xU-muK6DzKWYc3U4vwi4DYxcx
"""

# Rock, Scissor, Paper

import random

amount_of_games = int(input("How many games do you want to play? "))

comp_counter = 0
user_counter = 0

list_of_options = ('rock', 'scissor', 'paper')

for i in range(amount_of_games):
  user_choice = input("Please choose Rock, scissor or paper ").lower()
  comp_option = random.choice(list_of_options)

  if user_choice == 'rock' and comp_option == 'rock':
    print("Draw")
  elif user_choice == 'rock' and comp_option == 'scissor':
    print("User won a round")
    user_counter += 1
  elif user_choice == 'rock' and comp_option == 'paper':
    print("Computer won a round")
    comp_counter += 1
  elif user_choice == 'scissor' and comp_option == 'rock':
    print("Computer won a round")
    comp_counter += 1
  elif user_choice == 'scissor' and comp_option == 'scissor':
    print("Draw")
  elif user_choice == 'scissor' and comp_option == 'paper':
    print("User won a round")
    user_counter += 1
  elif user_choice == 'paper' and comp_option == 'rock':
    print("User won a round")
    user_counter += 1
  elif user_choice == 'paper' and comp_option == 'scissor':
    print("Computer won a round")
    comp_counter += 1
  elif user_choice == 'paper' and comp_option == 'paper':
    print("Draw")
  
if user_counter > comp_counter:
  print(f"Score is {user_counter} to {comp_counter}")
  print("Congratulation. You won a game")
elif user_counter < comp_counter:
  print(f"Score is {user_counter} to {comp_counter}")
  print("You lost a game")
else:
  print("Draw")